// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Group struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	OwnerID     uuid.NullUUID
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	HashedPassword string
	IsActive       sql.NullBool
}

type UsersGroup struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}
