// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Group struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	OwnerID     uuid.NullUUID
	InviteCode  string
	RulesInfo   string
}

type Post struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	GroupID      uuid.UUID
	Content      string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	ParentPostID uuid.NullUUID
	IsDeleted    sql.NullBool
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	HashedPassword string
	IsActive       sql.NullBool
}

type UsersGroup struct {
	UserID       uuid.UUID
	GroupID      uuid.UUID
	Role         string
	IsBanned     bool
	IsKicked     bool
	KickedUntil  sql.NullTime
	ModdedReason string
	ModdedAt     sql.NullTime
	ModdedBy     uuid.NullUUID
}
