-- +goose Up
ALTER TABLE users_groups
ADD COLUMN is_banned BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN is_kicked BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN kicked_until TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN modded_reason TEXT NOT NULL DEFAULT '',
ADD COLUMN modded_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN modded_by UUID REFERENCES users(id) ON DELETE SET NULL;

-- +goose Down
ALTER TABLE users_groups
DROP COLUMN is_banned,
DROP COLUMN is_kicked,
DROP COLUMN kicked_until,
DROP COLUMN modded_reason,
DROP COLUMN modded_at,
DROP COLUMN modded_by;